//! Connect a bot, spawn, name the blocks under its feet, then walk forward a few
//! blocks using the pathfinder + physics. Run with:
//! `cargo run --example spawn -- [host] [port] [username]`.

use std::collections::HashMap;

use ruststeve::bot::{Bot, BotEvent};
use ruststeve::protocol::ClientOptions;
use ruststeve::registry::{create_registry, BlockCollisionShapes, Registry};

#[tokio::main]
async fn main() -> std::io::Result<()> {
    let mut args = std::env::args().skip(1);
    let host = args.next().unwrap_or_else(|| "localhost".into());
    let port: u16 = args.next().and_then(|p| p.parse().ok()).unwrap_or(25565);
    let username = args.next().unwrap_or_else(|| "RustBot".into());

    // Load the registry generated by `cargo run --bin datagen` (block/item names,
    // collision shapes for physics/pathfinding). Falls back to an empty registry.
    let registry = create_registry("data", "26.1.2").unwrap_or_else(|_| {
        eprintln!("(no data/ — run `cargo run --bin datagen`; using empty registry)");
        Registry::build(
            vec![], vec![], vec![], vec![], vec![], vec![],
            BlockCollisionShapes::default(), HashMap::new(), "26.1.2",
        )
    });
    println!("registry: {} blocks, {} items", registry.blocks_array.len(), registry.items_array.len());

    println!("Connecting to {host}:{port} as {username}…");
    let options = ClientOptions { host, port, username, access_token: None, uuid: None };

    let mut bot = Bot::connect(options, &registry).await?;
    println!("Reached PLAY state. Waiting for spawn…");

    let mut walked = false;
    loop {
        match bot.next_event().await? {
            Some(BotEvent::Login) => println!(
                "login: entityId={} dimension={} maxPlayers={}",
                bot.entity.id, bot.game.dimension, bot.game.max_players
            ),
            Some(BotEvent::Spawn) => {
                let p = bot.entity.position;
                println!("SPAWNED at {p:?} — health={} food={}", bot.health, bot.food);
                bot.run_command("say hello from rustcraft").await?;
            }
            Some(BotEvent::ChunkLoad(cx, cz)) => {
                let p = bot.entity.position;
                let (px, py, pz) = (p.x as i32, p.y as i32, p.z as i32);
                if cx == px >> 4 && cz == pz >> 4 {
                    for dy in 1..=3 {
                        if let Some(info) = bot.block_at(px, py - dy, pz) {
                            println!("  block at ({px},{},{pz}) = {}", py - dy, info.name);
                        }
                    }
                    // Now that the area is loaded, walk a few blocks along +X.
                    if !walked {
                        walked = true;
                        let (tx, ty, tz) = (px + 4, py, pz);
                        println!("walking from ({px},{py},{pz}) to ({tx},{ty},{tz})…");
                        let arrived = bot.goto(tx, ty, tz).await?;
                        let q = bot.entity.position;
                        println!("goto arrived={arrived} — now at ({:.1},{:.1},{:.1})", q.x, q.y, q.z);
                    }
                }
            }
            Some(BotEvent::Health) => println!("health={} food={}", bot.health, bot.food),
            Some(BotEvent::Death) => println!("died"),
            Some(BotEvent::Kicked(reason)) => {
                println!("kicked: {reason}");
                break;
            }
            Some(_) => {}
            None => {
                println!("disconnected");
                break;
            }
        }
    }
    Ok(())
}
